# Generated by Django 4.0.4 on 2022-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Enroll_no', models.CharField(max_length=7)),
                ('Branch', models.CharField(max_length=3)),
            ],
        ),
    ]
